export const products = [
  {
    id: 1,
    imageUrl: "/product-images/breitsamer-alpenhonig-wuerzig-500g.png",
    imageBackground: "/images/pexels-casia-charlie-1270232-2421956.jpg",
    title: "Натуральный мёд",
    description: "Ароматный и полезный мёд из горного региона",
    price: 1200,
  },
  {
    id: 2,
    imageUrl: "/product-images/breitsamer-alpenhonig-bluete-cremig-500g.png",
    imageBackground: "/images/pexels-fotios-photos-2045295.jpg",
    title: "Цветочный мёд",
    description: "Собранный с полевых цветов, обладает нежным вкусом",
    price: 1400,
  },
  {
    id: 3,
    imageUrl: "/product-images/breitsamer-alpenhonig-wuerzig-500g.png",
    imageBackground: "/images/pexels-katlovessteve-551622.jpg",
    title: "Липовый мёд",
    description: "Обладает выраженным ароматом липы и лечебными свойствами",
    price: 1600,
  },
  {
    id: 4,
    imageUrl: "/product-images/breitsamer-alpenhonig-wuerzig-500g.png",
    imageBackground: "/images/pexels-pille-kirsi-222198-1116959.jpg",
    title: "Гречишный мёд",
    description: "Темный и насыщенный, богат железом и антиоксидантами",
    price: 1500,
  },
  {
    id: 5,
    imageUrl: "/product-images/breitsamer-honig-schmakerl-500g-b500-1.png",
    imageBackground: "/images/pexels-pixabay-63641.jpg",
    title: "Акациевый мёд",
    description: "Светлый, прозрачный, долго не кристаллизуется",
    price: 1700,
  },
  {
    id: 6,
    imageUrl:
      "/product-images/breitsamer-mediterraner-honig-andalusien-500g.png",
    imageBackground: "/images/pexels-pixabay-164470.jpg",
    title: "Лесной мёд",
    description: "Обладает насыщенным вкусом и содержит много полезных веществ",
    price: 1800,
  },
  {
    id: 7,
    imageUrl: "/product-images/breitsamer-schmankerl-honig-robinie.png",
    imageBackground: "/images/pexels-pixabay-460961.jpg",
    title: "Горный мёд",
    description: "Собранный на высокогорных лугах, обладает уникальным вкусом",
    price: 1900,
  },
  {
    id: 8,
    imageUrl: "/product-images/breitsamer-mediterraner-honig-toskana-500g.png",
    imageBackground: "/images/pexels-thijsvdw-998248.jpg",
    title: "Травяной мёд",
    description: "Смесь нектара различных луговых трав, полезен для иммунитета",
    price: 1750,
  },
  {
    id: 9,
    imageUrl:
      "/product-images/breitsamers-honigtopf-fruehlingsbluete-cremig-1000g.png",
    imageBackground: "/images/pexels-pixabay-63641.jpg",
    title: "Подсолнечный мёд",
    description: "Ярко-желтого цвета, быстро кристаллизуется, богат витаминами",
    price: 1300,
  },
  {
    id: 10,
    imageUrl: "/product-images/breitsamer-alpenhonig-bluete-cremig-500g.png",
    imageBackground: "/images/pexels-pille-kirsi-222198-1116959.jpg",
    title: "Луговой мёд",
    description: "Собран с полевых цветов, имеет насыщенный сладкий вкус",
    price: 1450,
  },
];
